version: '3'
services:
    selenoid:
        image: "aerokube/selenoid"       
        network_mode: bridge 
        ports:
            - "4444:4444"
        volumes:
            - C:\Users\andip\.jenkins\workspace\twsTest1\Selenoid:/etc/selenoid
            - /var/run/docker.sock:/var/run/docker.sock
            
    selenoid-ui:
        image: "aerokube/selenoid-ui"
        network_mode: bridge
        ports:
            - "8080:8080"
        links:
            -  selenoid
        command: 
            ["--selenoid-uri", "http://selenoid:4444"]
